#include<stdio.h>
#include<conio.h>
#include<stddef.h>
int main()
{
int i,j,k,l,m;
for(i=1;i<=1;i++)
{
    for(j=1;j<=6;j++)
    {
        printf("*");
    }printf("\n");
    for(k=1;k<=5;k++)
    {
        printf("*");
    }printf("\n");
    for(l=1;l<=4;l++)
    {
        printf("*");
    }printf("\n");
    for(m=1;m<=3;m++)
    {
        printf("*");
    }printf("\n");
    printf("**\n");
    printf("*");
}
    getch();
}